# Generated by Django 5.0.7 on 2024-07-31 17:57

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("fullname", models.CharField(max_length=150)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("PF", "Professor In Charge"),
                            ("MG", "Manager"),
                            ("CO", "Coordinator"),
                        ],
                        default="CO",
                        max_length=2,
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=100)),
                ("img_url", models.CharField(max_length=300)),
                ("linkedin", models.CharField(max_length=300)),
            ],
        ),
    ]
